language: python
python:
  - "3.7"
  - "3.8"
install:
  - pip install .
  - pip install flake8 pylint coveralls
script:
- flake8 androidtv/ && pylint androidtv/ && coverage run --source androidtv setup.py test
after_success:
- coveralls
